In [1]:
import pandas as pd
import numpy as np

In [2]:
submission = pd.read_csv("../data/sample_submission.csv")

In [3]:
submission.head()

   id  target
0   0  0.0364
1   1  0.0364
2   2  0.0364
3   3  0.0364
4   4  0.0364

In [4]:
submission.shape

(892816, 2)

In [5]:
train = pd.read_csv("../data/train.csv")
test = pd.read_csv("../data/test.csv")

In [8]:
train.head(10)

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,0,2,2,5,1,0,0,1,0,...,9,1,5,8,0,1,1,0,0,1
1,9,0,1,1,7,0,0,0,0,1,...,3,1,1,9,0,1,1,0,1,0
2,13,0,5,4,9,1,0,0,0,1,...,4,2,7,7,0,1,1,0,1,0
3,16,0,0,1,2,0,0,1,0,0,...,2,2,4,9,0,0,0,0,0,0
4,17,0,0,2,0,1,0,1,0,0,...,3,1,1,3,0,0,0,1,1,0
5,19,0,5,1,4,0,0,0,0,0,...,4,2,0,9,0,1,0,1,1,1
6,20,0,2,1,3,1,0,0,1,0,...,3,0,0,10,0,1,0,0,1,0
7,22,0,5,1,4,0,0,1,0,0,...,7,1,3,6,1,0,1,0,1,0
8,26,0,5,1,3,1,0,0,0,1,...,4,2,1,5,0,1,0,0,0,1
9,28,1,1,1,2,0,0,0,1,0,...,3,5,0,6,0,1,0,0,1,0

In [7]:
train.shape

(595212, 59)

In [9]:
test.head()

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,0,0,1,8,1,0,0,1,0,0,...,1,1,1,12,0,1,1,0,0,1
1,1,4,2,5,1,0,0,0,0,1,...,2,0,3,10,0,0,1,1,0,1
2,2,5,1,3,0,0,0,0,0,1,...,4,0,2,4,0,0,0,0,0,0
3,3,0,1,6,0,0,1,0,0,0,...,5,1,0,5,1,0,1,0,0,0
4,4,5,1,7,0,0,0,0,0,1,...,4,0,0,4,0,1,1,0,0,1

In [10]:
test.shape

(892816, 58)

In [11]:
train.describe()

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
count,5.952120e+05,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,...,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000
mean,7.438036e+05,0.036448,1.900378,1.358943,4.423318,0.416794,0.405188,0.393742,0.257033,0.163921,...,5.441382,1.441918,2.872288,7.539026,0.122427,0.627840,0.554182,0.287182,0.349024,0.153318
std,4.293678e+05,0.187401,1.983789,0.664594,2.699902,0.493311,1.350642,0.488579,0.436998,0.370205,...,2.332871,1.202963,1.694887,2.746652,0.327779,0.483381,0.497056,0.452447,0.476662,0.360295
min,7.000000e+00,0.000000,0.000000,-1.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.719915e+05,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,1.000000,2.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7.435475e+05,0.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.000000,1.000000,3.000000,7.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,1.115549e+06,0.000000,3.000000,2.000000,6.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,7.000000,2.000000,4.000000,9.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,1.488027e+06,1.000000,7.000000,4.000000,11.000000,1.000000,6.000000,1.000000,1.000000,1.000000,...,19.000000,10.000000,13.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [12]:
import xgboost as xgb

E:\anacoda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [17]:
result = pd.DataFrame()
params = {
        'eta': 0.1,
        'max_depth': 9,
        'objective': 'binary:logistic',
        'eval_metric': 'logloss',
        'seed': 0,
        'silent': 1
}
clos=[x for x in train.columns if x not in ['target', 'id']]  
xgbtrain = xgb.DMatrix(train[clos], train['target'])
xgbtest = xgb.DMatrix(test[clos])
watchlist = [(xgbtrain, 'train'), (xgbtrain, 'test')]
num_rounds = 150
model = xgb.train(params, xgbtrain, num_rounds, watchlist, early_stopping_rounds=50) 
test['target'] = model.predict(xgbtest, ntree_limit=model.best_ntree_limit)
r=test[['id','target']]
result=pd.concat([result,r])
result['id']=result['id'].astype('int')
result.to_csv("../result/result_v1.csv", index=False)

[0]	train-logloss:0.611324	test-logloss:0.611324
Multiple eval metrics have been passed: 'test-logloss' will be used for early stopping.

Will train until test-logloss hasn't improved in 50 rounds.
[1]	train-logloss:0.544394	test-logloss:0.544394
[2]	train-logloss:0.488768	test-logloss:0.488768
[3]	train-logloss:0.442013	test-logloss:0.442013
[4]	train-logloss:0.402352	test-logloss:0.402352
[5]	train-logloss:0.368445	test-logloss:0.368445
[6]	train-logloss:0.339322	test-logloss:0.339322
[7]	train-logloss:0.314203	test-logloss:0.314203
[8]	train-logloss:0.292419	test-logloss:0.292419
[9]	train-logloss:0.273546	test-logloss:0.273546
[10]	train-logloss:0.257118	test-logloss:0.257118
[11]	train-logloss:0.242811	test-logloss:0.242811
[12]	train-logloss:0.230312	test-logloss:0.230312
[13]	train-logloss:0.21937	test-logloss:0.21937
[14]	train-logloss:0.209829	test-logloss:0.209829
[15]	train-logloss:0.201496	test-logloss:0.201496
[16]	train-logloss:0.194197	test-logloss:0.194197
[17]	train-logloss:0.187784	test-logloss:0.187784
[18]	train-logloss:0.182179	test-logloss:0.182179
[19]	train-logloss:0.17727	test-logloss:0.17727
[20]	train-logloss:0.172981	test-logloss:0.172981
[21]	train-logloss:0.16925	test-logloss:0.16925
[22]	train-logloss:0.16596	test-logloss:0.16596
[23]	train-logloss:0.163042	test-logloss:0.163042
[24]	train-logloss:0.160527	test-logloss:0.160527
[25]	train-logloss:0.158279	test-logloss:0.158279
[26]	train-logloss:0.156328	test-logloss:0.156328
[27]	train-logloss:0.154599	test-logloss:0.154599
[28]	train-logloss:0.153062	test-logloss:0.153062
[29]	train-logloss:0.151707	test-logloss:0.151707
[30]	train-logloss:0.150496	test-logloss:0.150496
[31]	train-logloss:0.14939	test-logloss:0.14939
[32]	train-logloss:0.148416	test-logloss:0.148416
[33]	train-logloss:0.147532	test-logloss:0.147532
[34]	train-logloss:0.146731	test-logloss:0.146731
[35]	train-logloss:0.146008	test-logloss:0.146008
[36]	train-logloss:0.145339	test-logloss:0.145339
[37]	train-logloss:0.144728	test-logloss:0.144728
[38]	train-logloss:0.144123	test-logloss:0.144123
[39]	train-logloss:0.143567	test-logloss:0.143567
[40]	train-logloss:0.143046	test-logloss:0.143046
[41]	train-logloss:0.142557	test-logloss:0.142557
[42]	train-logloss:0.142166	test-logloss:0.142166
[43]	train-logloss:0.141727	test-logloss:0.141727
[44]	train-logloss:0.141267	test-logloss:0.141267
[45]	train-logloss:0.140818	test-logloss:0.140818
[46]	train-logloss:0.140479	test-logloss:0.140479
[47]	train-logloss:0.140048	test-logloss:0.140048
[48]	train-logloss:0.139774	test-logloss:0.139774
[49]	train-logloss:0.139407	test-logloss:0.139407
[50]	train-logloss:0.139044	test-logloss:0.139044
[51]	train-logloss:0.138662	test-logloss:0.138662
[52]	train-logloss:0.138279	test-logloss:0.138279
[53]	train-logloss:0.138038	test-logloss:0.138038
[54]	train-logloss:0.137688	test-logloss:0.137688
[55]	train-logloss:0.137292	test-logloss:0.137292
[56]	train-logloss:0.137055	test-logloss:0.137055
[57]	train-logloss:0.136764	test-logloss:0.136764
[58]	train-logloss:0.136439	test-logloss:0.136439
[59]	train-logloss:0.136099	test-logloss:0.136099
[60]	train-logloss:0.135865	test-logloss:0.135865
[61]	train-logloss:0.135555	test-logloss:0.135555
[62]	train-logloss:0.135265	test-logloss:0.135265
[63]	train-logloss:0.135019	test-logloss:0.135019
[64]	train-logloss:0.134692	test-logloss:0.134692
[65]	train-logloss:0.134465	test-logloss:0.134465
[66]	train-logloss:0.13417	test-logloss:0.13417
[67]	train-logloss:0.133925	test-logloss:0.133925
[68]	train-logloss:0.133676	test-logloss:0.133676
[69]	train-logloss:0.1334	test-logloss:0.1334
[70]	train-logloss:0.133043	test-logloss:0.133043
[71]	train-logloss:0.132822	test-logloss:0.132822
[72]	train-logloss:0.132727	test-logloss:0.132727
[73]	train-logloss:0.132521	test-logloss:0.132521
[74]	train-logloss:0.132274	test-logloss:0.132274
[75]	train-logloss:0.131926	test-logloss:0.131926
[76]	train-logloss:0.131718	test-logloss:0.131718
[77]	train-logloss:0.131489	test-logloss:0.131489
[78]	train-logloss:0.131136	test-logloss:0.131136
[79]	train-logloss:0.13094	test-logloss:0.13094
[80]	train-logloss:0.130741	test-logloss:0.130741
[81]	train-logloss:0.130486	test-logloss:0.130486
[82]	train-logloss:0.130189	test-logloss:0.130189
[83]	train-logloss:0.129951	test-logloss:0.129951
[84]	train-logloss:0.129735	test-logloss:0.129735
[85]	train-logloss:0.12968	test-logloss:0.12968
[86]	train-logloss:0.129489	test-logloss:0.129489
[87]	train-logloss:0.129187	test-logloss:0.129187
[88]	train-logloss:0.129025	test-logloss:0.129025
[89]	train-logloss:0.128958	test-logloss:0.128958
[90]	train-logloss:0.128775	test-logloss:0.128775
[91]	train-logloss:0.128516	test-logloss:0.128516
[92]	train-logloss:0.12822	test-logloss:0.12822
[93]	train-logloss:0.127963	test-logloss:0.127963
[94]	train-logloss:0.127653	test-logloss:0.127653
[95]	train-logloss:0.127543	test-logloss:0.127543
[96]	train-logloss:0.127277	test-logloss:0.127277
[97]	train-logloss:0.127246	test-logloss:0.127246
[98]	train-logloss:0.127042	test-logloss:0.127042
[99]	train-logloss:0.126776	test-logloss:0.126776
[100]	train-logloss:0.126549	test-logloss:0.126549
[101]	train-logloss:0.126385	test-logloss:0.126385
[102]	train-logloss:0.126139	test-logloss:0.126139
[103]	train-logloss:0.125868	test-logloss:0.125868
[104]	train-logloss:0.125738	test-logloss:0.125738
[105]	train-logloss:0.125542	test-logloss:0.125542
[106]	train-logloss:0.125413	test-logloss:0.125413
[107]	train-logloss:0.125199	test-logloss:0.125199
[108]	train-logloss:0.125129	test-logloss:0.125129
[109]	train-logloss:0.124964	test-logloss:0.124964
[110]	train-logloss:0.124749	test-logloss:0.124749
[111]	train-logloss:0.124653	test-logloss:0.124653
[112]	train-logloss:0.124341	test-logloss:0.124341
[113]	train-logloss:0.124196	test-logloss:0.124196
[114]	train-logloss:0.124084	test-logloss:0.124084
[115]	train-logloss:0.123856	test-logloss:0.123856
[116]	train-logloss:0.123777	test-logloss:0.123777
[117]	train-logloss:0.123624	test-logloss:0.123624
[118]	train-logloss:0.123515	test-logloss:0.123515
[119]	train-logloss:0.12349	test-logloss:0.12349
[120]	train-logloss:0.1233	test-logloss:0.1233
[121]	train-logloss:0.123127	test-logloss:0.123127
[122]	train-logloss:0.12293	test-logloss:0.12293
[123]	train-logloss:0.122756	test-logloss:0.122756
[124]	train-logloss:0.122743	test-logloss:0.122743
[125]	train-logloss:0.122641	test-logloss:0.122641
[126]	train-logloss:0.122447	test-logloss:0.122447
[127]	train-logloss:0.12232	test-logloss:0.12232
[128]	train-logloss:0.122183	test-logloss:0.122183
[129]	train-logloss:0.122122	test-logloss:0.122122
[130]	train-logloss:0.121954	test-logloss:0.121954
[131]	train-logloss:0.121775	test-logloss:0.121775
[132]	train-logloss:0.121633	test-logloss:0.121633
[133]	train-logloss:0.121603	test-logloss:0.121603
[134]	train-logloss:0.121492	test-logloss:0.121492
[135]	train-logloss:0.12135	test-logloss:0.12135
[136]	train-logloss:0.121325	test-logloss:0.121325
[137]	train-logloss:0.121288	test-logloss:0.121288
[138]	train-logloss:0.121177	test-logloss:0.121177
[139]	train-logloss:0.120925	test-logloss:0.120925
[140]	train-logloss:0.120688	test-logloss:0.120688
[141]	train-logloss:0.120551	test-logloss:0.120551
[142]	train-logloss:0.120483	test-logloss:0.120483
[143]	train-logloss:0.120378	test-logloss:0.120378
[144]	train-logloss:0.120077	test-logloss:0.120077
[145]	train-logloss:0.119963	test-logloss:0.119963
[146]	train-logloss:0.119828	test-logloss:0.119828
[147]	train-logloss:0.119682	test-logloss:0.119682
[148]	train-logloss:0.119367	test-logloss:0.119367
[149]	train-logloss:0.11921	test-logloss:0.11921

In [18]:
result = pd.read_csv("../result/result_v1.csv")

In [19]:
result.head()

   id    target
0   0  0.023996
1   1  0.023558
2   2  0.019387
3   3  0.017575
4   4  0.038432